version: '3.1'

services:
  grafana:
    image: grafana/grafana:6.7.2
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
  influxdb:
    image: influxdb:1.7-alpine
    restart: always
    environment:
      INFLUXDB_DB: telemac
      INFLUXDB_GRAPHITE_ENABLED: 'true'
    ports:
      - 127.0.0.1:8086:8086
      - 127.0.0.1:2003:2003
    volumes:
      - ./influxdb/data:/var/lib/influxdb
